package cn.atcast.crm.domain;

// Generated 2016-2-18 11:51:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SysRole generated by hbm2java
 */
public class SysRole implements java.io.Serializable {

	private Long roleId;
	private String roleName;
	private String roleMemo;
	//一个角色可以分配给多个用户
	private Set sysUsers = new HashSet(0);

	public SysRole() {
	}

	public SysRole(String roleName) {
		this.roleName = roleName;
	}

	public SysRole(String roleName, String roleMemo, Set sysUsers) {
		this.roleName = roleName;
		this.roleMemo = roleMemo;
		this.sysUsers = sysUsers;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleMemo() {
		return this.roleMemo;
	}

	public void setRoleMemo(String roleMemo) {
		this.roleMemo = roleMemo;
	}

	public Set getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(Set sysUsers) {
		this.sysUsers = sysUsers;
	}

}
