package cn.atcast.crm.domain;

// Generated 2016-2-18 11:51:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SysUser generated by hbm2java
 */
public class SysUser implements java.io.Serializable {

	private Long userId;
	private String userCode;
	private String userName;
	private String userPassword;
	private String userState;
	//客户拜访记录
	private Set saleVisits = new HashSet(0);
	//一个用户可以有多个角色
	private Set sysRoles = new HashSet(0);

	

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

	
	public Set getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(Set sysRoles) {
		this.sysRoles = sysRoles;
	}

	public Set getSaleVisits() {
		return saleVisits;
	}

	public void setSaleVisits(Set saleVisits) {
		this.saleVisits = saleVisits;
	}


}
